// Tier-1 server-side generator. Replicates profile.html renderProfile from /api/profiles/:id data,
// emits lean /profile/{id}/index.html referencing shared /assets/profile-page.{css,js}. Parity is
// proven by the 25-page headless diff (the gate), not assumed.
const fs = require('fs'), path = require('path'), https = require('https');
const OUT = process.env.OUT_DIR || '/Users/arthurkostaras/projects/canadaaccountants';
const API = 'https://canadaaccountants-backend-production-1d8f.up.railway.app';
const IDS = fs.readFileSync(process.env.IDS_FILE || '/tmp/tier1/ids.txt', 'utf8').split('\n').filter(Boolean);
const LIMIT = process.env.LIMIT ? parseInt(process.env.LIMIT) : IDS.length;
const CONC = 12;

// Phronisi provenance footer (Lane B, 2026-07-13). PHRONISI_ENTITY must hold the
// confirmed legal entity name before any generation run; the CLI path below refuses
// to run while it is null so a placeholder can never reach a public page. buildPage
// stays callable for previews (preview-claimed.js) with a visible pending marker.
const PHRONISI_ENTITY = 'Phronisi'; // confirmed by Arthur 2026-07-13: brand name as operator, no legal suffix
const entityDisplay = PHRONISI_ENTITY ? `${PHRONISI_ENTITY}${/\.$/.test(PHRONISI_ENTITY) ? '' : '.'}` : '[entity name pending].';
const provenanceFooter = `
    <footer style="padding:32px 24px;text-align:center;border-top:1px solid rgba(241,234,220,0.08);">
        <p style="color:var(--text-secondary);font-size:12px;max-width:720px;margin:0 auto 10px;">CanadaAccountants.app is part of the Phronisi network of Canadian professional platforms: CanadaAccountants, CanadaLawyers, CanadaInvesting, and Canada Business Exits. Operated by ${entityDisplay}</p>
        <p style="font-size:12px;margin:0;"><a href="https://phronisi.app" rel="noopener" style="color:var(--text-secondary);text-decoration:none;">Built by Phronisi</a></p>
    </footer>`;

const getInitials = n => String(n || '').split(' ').filter(Boolean).map(w => w[0]).join('').toUpperCase().slice(0, 2);
const getScoreColor = s => s >= 80 ? 'var(--success)' : s >= 60 ? 'var(--gold)' : s >= 40 ? 'var(--gold-bright)' : 'var(--danger)';
function fetchJSON(url) {
  return new Promise((res, rej) => {
    https.get(url, r => { let d = ''; r.on('data', c => d += c); r.on('end', () => { try { res({ status: r.statusCode, json: JSON.parse(d) }); } catch (e) { rej(e); } }); }).on('error', rej);
  });
}

function buildPage(data, id) {
  const p = data.profile;
  const seo = data.seo_score || { score: 0, grade: 'D', recommendations: [] };
  const scoreColor = getScoreColor(seo.score);
  const designations = (p.designation || '').split(/[,\/]/).map(d => d.trim()).filter(Boolean);
  const designationBadges = designations.length
    ? designations.map(d => `<span class="badge badge-designation"><i class="fas fa-award"></i> ${d}</span>`).join('')
    : '<span class="badge badge-designation"><i class="fas fa-user-tie"></i> CPA</span>';
  const claimBadge = p.claimed
    ? '<span class="badge badge-claimed"><i class="fas fa-check-circle"></i> Claimed Profile</span>'
    : '<span class="badge badge-unclaimed"><i class="fas fa-info-circle"></i> Unclaimed &mdash; Basic Listing</span>';
  const firmDisplay = p.firm_name || `Listed in ${p.province || 'Canadian'} CPA directory`;
  const location = [p.city, p.province].filter(Boolean).join(', ');
  let bioHtml;
  if (p.bio) {
    bioHtml = `<div class="bio-text">${p.bio.replace(/\n\n/g, '</p><p class="bio-text" style="margin-top:12px;">').replace(/\n/g, '<br>')}</div>
                    <p class="bio-note"><i class="fas fa-info-circle"></i> Generated by AI from CPA directory data</p>`;
  } else {
    bioHtml = `<div class="bio-loading"><i class="fas fa-spinner fa-spin"></i> Bio is being generated...</div>`;
  }
  const recHtml = (seo.recommendations || []).slice(0, 5).map(r => {
    const ic = r.impact === 'high' ? 'rec-high' : r.impact === 'medium' ? 'rec-medium' : 'rec-low';
    return `<li class="recommendation-item">
                    <span class="rec-icon ${ic}"><i class="fas fa-plus"></i></span>
                    <span>${r.action}</span>
                    <span class="rec-points">+${r.points} pts</span>
                </li>`;
  }).join('');
  const claimUrl = p.ref_token ? `claim-profile?ref=${p.ref_token}` : `claim-profile`;
  const pageContent = `
                <!-- Profile Hero -->
                <section class="profile-hero">
                    <div class="profile-avatar">${getInitials(p.name)}</div>
                    <h1 class="profile-name">${p.name}${p.founding_member ? '<span style="display:inline-block;background:var(--gold);color:var(--ink);font-size:11px;font-weight:700;padding:4px 10px;border-radius:12px;margin-left:8px;text-transform:uppercase;letter-spacing:0.5px;">Founding Member</span>' : ''}</h1>
                    <p class="profile-firm">${firmDisplay}</p>
                    ${location ? `<p class="profile-location"><i class="fas fa-map-marker-alt"></i> ${location}</p>` : ''}
                    <div class="badges">
                        ${designationBadges}
                        ${claimBadge}
                    </div>
                </section>

                <div class="profile-content">
                    <div class="section-card">
                        <div class="section-header">
                            <div class="section-icon"><i class="fas fa-robot"></i></div>
                            <div>
                                <div class="section-title">AI-Generated Professional Bio</div>
                                <div class="section-subtitle">Created from CPA directory data</div>
                            </div>
                        </div>
                        ${bioHtml}
                    </div>

                    <div class="section-card">
                        <div class="section-header">
                            <div class="section-icon"><i class="fas fa-chart-line"></i></div>
                            <div>
                                <div class="section-title">Profile Score</div>
                                <div class="section-subtitle">How complete and optimized this profile is</div>
                            </div>
                        </div>
                        <div class="score-section">
                            <div class="score-circle-container">
                                <div class="score-circle" style="--score: ${seo.score}; background: conic-gradient(${scoreColor} ${seo.score * 3.6}deg, rgba(241,234,220,0.08) 0deg);">
                                    <div class="score-circle-inner">
                                        <div class="score-number" style="color: ${scoreColor};">${seo.score}</div>
                                        <div class="score-label">/ 100</div>
                                    </div>
                                </div>
                                <div class="score-grade">Grade ${seo.grade}</div>
                            </div>
                            <div class="score-details">
                                ${seo.recommendations.length > 0 ? `
                                    <h4>What's Missing</h4>
                                    <ul class="recommendation-list">${recHtml}</ul>
                                    <p class="score-cta-text">Take control of this profile to improve the score.</p>
                                ` : `
                                    <h4>Excellent!</h4>
                                    <p style="color: var(--text-secondary);">This profile is fully optimized.</p>
                                `}
                            </div>
                        </div>
                    </div>

                    <div class="section-card cta-section">
                        <h2>Take Control of Your Profile</h2>
                        <p>Edit your bio, add specializations, and manage what clients see.</p>
                        <a href="${claimUrl}" class="btn-cta">Take Control <i class="fas fa-arrow-right"></i></a>
                        ${!p.claimed ? `<div style="margin-top:14px;"><button id="organicClaimBtn" data-pid="${p.id}" class="btn-cta" style="background:transparent;border:1px solid var(--gold);color:var(--gold);cursor:pointer;">Is this you? Claim this profile</button><div id="organicClaimMsg" style="display:none;margin-top:10px;font-size:14px;color:var(--success);"></div></div>` : ''}
                    </div>
                </div>`;
  const title = `${p.name} — CPA Profile | CanadaAccountants.app`;
  const metaDesc = `View ${p.name}'s CPA profile on CanadaAccountants.app. ${p.designation || 'CPA'} in ${[p.city, p.province].filter(Boolean).join(', ') || 'Canada'}.`;
  const canon = `https://canadaaccountants.app/profile/${id}/`;
  const jsonld = JSON.stringify(data.structured_data || {});
  return `<!DOCTYPE html>
<html lang="en">
<head>
    <base href="https://canadaaccountants.app/">
    <script src="js/api-config.js"></script>
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-Q289QTZ71B"></script>
    <script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','G-Q289QTZ71B');</script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0, user-scalable=yes">
    <meta name="description" content="${metaDesc.replace(/"/g, '&quot;')}">
    <link rel="canonical" href="${canon}">
    <meta property="og:type" content="profile">
    <meta property="og:url" content="${canon}">
    <meta property="og:title" content="${title.replace(/"/g, '&quot;')}">
    <meta property="og:description" content="${metaDesc.replace(/"/g, '&quot;')}">
    <meta property="og:image" content="https://canadaaccountants.app/icon-512.png">
    <meta property="og:site_name" content="CanadaAccountants">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,500;0,600;0,700;1,500&family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/assets/phronisi-tokens.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="/assets/profile-page.css">
    <title>${title}</title>
<style id="phronisi-type">body{font-family:var(--font-body)}h1,h2,h3,.section-title{font-family:var(--font-display)}</style>
</head>
<body>
    <nav class="nav">
        <div class="nav-inner">
            <a href="/" class="nav-logo"><i class="fas fa-maple-leaf maple"></i> CanadaAccountants<span style="color: var(--primary-blue)">.app</span></a>
            <button class="nav-toggle" onclick="document.querySelector('.nav-links').classList.toggle('active')" aria-label="Menu"><i class="fas fa-bars"></i></button>
            <div class="nav-links">
                <a href="find-cpa">Find CPA</a>
                <a href="why-we-win">Why We Win</a>
                <a href="pricing">Pricing</a>
                <a href="contact">Contact</a>
                <a href="cpa-login">Login</a>
                <a href="join-as-cpa" class="nav-cta">Apply to Join</a>
            </div>
        </div>
    </nav>
    <div id="page-content">${pageContent}</div>${provenanceFooter}
    <script id="jsonld-script" type="application/ld+json">${jsonld}</script>
    <script src="/assets/profile-page.js"></script>
</body>
</html>`;
}

module.exports = { buildPage };
if (require.main !== module) return;
(async () => {
  if (!PHRONISI_ENTITY) {
    console.error('REFUSED: PHRONISI_ENTITY is not set. Expected the confirmed legal entity name for the "Operated by" network disclosure; got null. Fix: set PHRONISI_ENTITY at the top of this file once Arthur confirms the entity name, then re-run. No pages were generated.');
    process.exit(1);
  }
  const ids = IDS.slice(0, LIMIT);
  let ok = 0, fail = 0, gone = 0;
  for (let i = 0; i < ids.length; i += CONC) {
    const batch = ids.slice(i, i + CONC);
    await Promise.all(batch.map(async id => {
      try {
        const { status, json } = await fetchJSON(`${API}/api/profiles/${id}`);
        if (status === 410) { gone++; return; }
        if (status !== 200 || !json.profile) { fail++; return; }
        const html = buildPage(json, id);
        const dir = path.join(OUT, 'profile', String(id));
        fs.mkdirSync(dir, { recursive: true });
        fs.writeFileSync(path.join(dir, 'index.html'), html);
        ok++;
      } catch (e) { fail++; }
    }));
    if (i % 600 === 0) process.stdout.write(`  ...${i + batch.length}/${ids.length} (ok=${ok} fail=${fail} gone=${gone})\n`);
  }
  console.log(`DONE: generated ${ok}, failed ${fail}, gated/410 ${gone}, of ${ids.length}`);
})();
